### ISSUE TITLE
What is the difference between AE and DM?

### ISSUE THREAD

**Issue by cpy0029** [nku-zhichengzhang/ExtDM#1]
What is the difference between AE and DM?

**Comment by nku-zhichengzhang** [comment]
The ExtDM is similar to the LDM paradigm and trains AE as well as DM sequentially.

AE&DM are two types of widely used techniques in generative AI and the corresponding full names are autoencoder and diffusion models, respectively.

For more details, please refer to the paper of LDM (https://arxiv.org/abs/2112.10752) and our work (https://openaccess.thecvf.com/content/CVPR2024/papers/Zhang_ExtDM_Distribution_Extrapolation_Diffusion_Model_for_Video_Prediction_CVPR_2024_paper.pdf).
