### ISSUE TITLE
Version conflict for rotary_embedding_torch

### ISSUE THREAD

**Issue by chenshitinghah** [nku-zhichengzhang/ExtDM#4]
Hi, could you tell me what is the version of rotary_embedding_torch in your code?
      In the 'Environment Setup' part: 'rotary_embedding_torch==rotary-embedding-torch'.
      And if  'pip install rotary_embedding_torch', the latest version will be installed, and there is a conflict between rotary_embedding_torch and pytorch.

**Comment by nku-zhichengzhang** [comment]
we use 0.2.1
