### ISSUE TITLE
SMMNIST and KTH datasets' google drive download links are dead

### ISSUE THREAD

**Issue by daleigehhh** [nku-zhichengzhang/ExtDM#6]
@JunyaoHu 
Hi there, thanks for your execellent work, I appreciated it. I am new to video prediction, and the google drive links for SMMNIST and KTH dataset you presented in the README are dead. I am wondering are these two datasets generated automatically in the code or I must download them from somewhere else. 
Thanks

**Comment by nku-zhichengzhang** [comment]
SMMNIST is generated according to the MCVD code. KTH can be downloaded from its official website.
