### ISSUE TITLE
About the AutoEncoder

### ISSUE THREAD

**Issue by daleigehhh** [nku-zhichengzhang/ExtDM#7]
@nku-zhichengzhang 
Hi, can you provide more information about the autoencoder you are using, I see you mentioned you followed the structure of the paper "Perceptual Loss", but the motion cue AE seems more complicated then the the paper.

**Comment by nku-zhichengzhang** [comment]
Thanks for the reminder, we use a similar architecture implemented by LFDM, CVPRR24.
